name: Hono Jest

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Run Jest
        run: npm run test
        working-directory: hono
